
const $=s=>document.querySelector(s),state={data:null,zone:null,selected:null};document.addEventListener('DOMContentLoaded',init);
async function init(){$('#refreshBtn').onclick=()=>load(true);$('#exportBtn').onclick=()=>print();$('#zoneSelect').onchange=e=>{state.zone=e.target.value;renderAll()};$('#searchInput').addEventListener('input',renderHeat);await load();setInterval(()=>load(true),WMS.config.REFRESH_MS||120000)}
async function load(force=false){status('loading','Carregando');try{state.data=await WMS.load(force);const zs=WMS.zones(state.data);if(!zs.length)throw new Error('A API não retornou zonas');state.zone=zs.includes(state.zone)?state.zone:(zs.includes(WMS.config.DEFAULT_ZONE)?WMS.config.DEFAULT_ZONE:zs[0]);$('#zoneSelect').innerHTML=zs.map(z=>`<option value="${z}">${state.data.meta?.[z]?.label||`Zona ${z}`}</option>`).join('');$('#zoneSelect').value=state.zone;renderAll();status('ok',WMS.config.SHEET_API_URL?'Google Sheets conectado':'Modo local')}catch(e){status('error','Erro na conexão');toast(e.message);console.error(e)}}
function cells(){return state.data.cells.filter(x=>String(x.Zona)===String(state.zone))}function roads(){return state.data.corridors.filter(x=>String(x.Zona)===String(state.zone))}
function renderAll(){renderKpis();renderHeat();renderRanking();renderInsights();renderDetail()}
function renderKpis(){const z=state.data.zones.find(x=>String(x.Zona)===String(state.zone))||{};const a=[['Ocupação',pct(z.occ_pct),'posição útil'],['Posições totais',WMS.fmt(z.total),'inclui bloqueadas'],['Ocupadas',WMS.fmt(z.ocupado),'com estoque'],['Disponíveis',WMS.fmt(z.disponivel),'livres para uso'],['Bloqueadas',WMS.fmt(z.bloqueado),'fora do cálculo']];$('#kpis').innerHTML=a.map(x=>`<div class="kpi card"><small>${x[0]}</small><strong>${x[1]}</strong><span>${x[2]}</span></div>`).join('')}
function renderHeat(){if(!state.data)return;const q=$('#searchInput').value.trim().toUpperCase(),p=parse(q);if(p.zone&&WMS.zones(state.data).includes(p.zone)&&p.zone!==state.zone){state.zone=p.zone;$('#zoneSelect').value=p.zone}const cs=cells(),ls=[...new Set(cs.map(x=>Number(x.nivel)))].sort((a,b)=>a-b),all=[...new Set(cs.map(x=>Number(x.rua_num)))].sort((a,b)=>a-b),rs=p.road?all.filter(r=>r===p.road):(q&&/^\d+$/.test(q)?all.filter(r=>String(r).includes(q)):all),map=new Map(cs.map(c=>[`${+c.rua_num}|${+c.nivel}`,c]));const head=`<tr><th>Rua</th>${ls.map(l=>`<th>N${pad(l)}</th>`).join('')}<th>Total rua</th></tr>`;const body=rs.map(r=>{const road=roads().find(x=>+x.rua_num===r),td=ls.map(l=>{const c=map.get(`${r}|${l}`);return c?`<td class="heat-cell ${WMS.cls(c.occ_pct)}" data-r="${r}" data-l="${l}"><strong>${pct(c.occ_pct)}</strong><span>${WMS.fmt(c.ocupado)} / ${WMS.fmt(c.disponivel)}</span></td>`:`<td class="heat-cell blocked"><strong>—</strong><span>sem dado</span></td>`}).join(''),tot=road?`<td class="heat-cell ${WMS.cls(road.occ_pct)}" data-r="${r}" data-l="0"><strong>${pct(road.occ_pct)}</strong><span>${WMS.fmt(road.total)} posições</span></td>`:'<td></td>';return`<tr><td>Rua ${pad(r)}</td>${td}${tot}</tr>`}).join('');$('#heatmap').innerHTML=rs.length?`<table class="heat-table">${head}${body}</table>`:'Nenhuma rua encontrada';document.querySelectorAll('[data-r]').forEach(e=>e.onclick=()=>select(+e.dataset.r,+e.dataset.l))}
function renderRanking(){const a=roads().slice().sort((a,b)=>(b.occ_pct??-1)-(a.occ_pct??-1)).slice(0,8);$('#ranking').innerHTML=a.map((r,i)=>`<div class="rank-row"><div class="rank-num">${i+1}</div><div><strong>Rua ${pad(r.rua_num)}</strong><div class="rank-bar"><i style="width:${Math.max(0,Math.min(100,+r.occ_pct||0))}%"></i></div></div><b>${pct(r.occ_pct)}</b></div>`).join('')}
function renderInsights(){const rs=roads().filter(r=>r.occ_pct!=null),crit=rs.filter(r=>r.occ_pct>=90),free=rs.slice().sort((a,b)=>(a.occ_pct??999)-(b.occ_pct??999))[0],blocked=cells().reduce((s,c)=>s+(+c.bloqueado||0),0);const a=[crit.length?`${crit.length} rua(s) acima de 90% exigem atenção.`:'Nenhuma rua crítica acima de 90%.',free?`Maior folga: Rua ${pad(free.rua_num)} com ${pct(free.occ_pct)}.`:'Sem dados para folga.',`${WMS.fmt(blocked)} posições bloqueadas na zona.`];$('#insights').innerHTML=a.map(t=>`<div class="insight">${t}</div>`).join('')}
function select(r,l){state.selected=l?cells().find(c=>+c.rua_num===r&&+c.nivel===l):roads().find(c=>+c.rua_num===r);renderDetail()}
function renderDetail(){const c=state.selected;if(!c){$('#detailGrid').className='detail-grid empty';$('#detailGrid').textContent='Nenhuma célula selecionada.';return}$('#detailSubtitle').textContent=`Zona ${c.Zona} · Rua ${pad(c.rua_num)}${+c.nivel?` · Nível ${pad(c.nivel)}`:''}`;const a=[['Zona',c.Zona],['Rua',pad(c.rua_num)],['Nível',+c.nivel?pad(c.nivel):'Consolidado'],['Ocupação',pct(c.occ_pct)],['Ocupadas',WMS.fmt(c.ocupado)],['Disponíveis',WMS.fmt(c.disponivel)],['Bloqueadas',WMS.fmt(c.bloqueado)],['Peças',WMS.fmt(c.qtd_pecas)]];$('#detailGrid').className='detail-grid';$('#detailGrid').innerHTML=a.map(x=>`<div class="metric"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('')+`<div class="metric"><small>Ação</small><strong><a href="3d.html?zone=${c.Zona}&road=${c.rua_num}&level=${c.nivel||'all'}">Abrir no 3D →</a></strong></div>`}
function parse(q){const m=q.match(/([A-Z0-9]+)[-_\/](\d+)[-_\/](\d+)/);if(m)return{zone:m[1],road:+m[2],level:+m[3]};const r=q.match(/RUA\s*(\d+)/);return r?{road:+r[1]}:{}}function pct(v){return v==null?'—':`${Number(v).toLocaleString('pt-BR',{maximumFractionDigits:1})}%`}function pad(v){return String(+v).padStart(2,'0')}function status(c,t){$('#status').className=`status ${c}`;$('#status').innerHTML=`<i></i>${t}`}function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3500)}
