const $=s=>document.querySelector(s),ZONES=['A','B','HV','HS'];let reportData;
document.addEventListener('DOMContentLoaded',init);
async function init(){$('#zoneFilter').onchange=render;$('#statusFilter').onchange=render;$('#copyImageBtn').onclick=copyImage;$('#exportPdfBtn').onclick=exportPdf;try{reportData=await WMS.load();render();status('Google Sheets conectado')}catch(e){console.error(e);status('Falha ao carregar',true);$('#reportMatrix').textContent=e.message}}
function source(){const zf=$('#zoneFilter').value,range=$('#statusFilter').value,zones=zf==='ALL'?ZONES.filter(z=>reportData.zones.some(x=>x.Zona===z)):[zf];return{zones,corridors:reportData.corridors.filter(x=>zones.includes(String(x.Zona))&&Number(x.usable_positions)>0&&Number(x.piece_limit)>0&&match(x,range))}}
function render(){if(!reportData)return;const {zones,corridors}=source(),a=corridors.reduce((s,x)=>{s.limit+=+x.piece_limit||0;s.real+=+x.real_pieces||0;s.available+=+x.available_pieces||0;return s},{limit:0,real:0,available:0}),occ=a.limit?a.real/a.limit*100:null,critical=corridors.filter(x=>+x.occ_pct>=90).length;$('#reportDate').textContent=`Base atualizada em ${date(reportData.generated_at)} · ${corridors.length} ruas utilizáveis exibidas`;$('#reportKpis').innerHTML=[['Quantidade real',num(a.real),'Peças em posições utilizáveis'],['Ocupação',pct(occ),`${num(a.real)} de ${num(a.limit)} peças`],['Capacidade disponível',num(a.available),'Peças que ainda podem ser armazenadas'],['Ruas críticas',String(critical),'Acima de 90% de ocupação']].map(x=>`<article><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('');matrix(corridors,zones)}
function matrix(rows,zones){const map=new Map(rows.map(x=>[`${x.Zona}|${x.rua_num}`,x])),roads=[...new Set(rows.map(x=>+x.rua_num))].sort((a,b)=>a-b);if(!roads.length){$('#reportMatrix').textContent='Nenhuma rua utilizável corresponde aos filtros selecionados.';return}$('#reportMatrix').innerHTML=`<table><thead><tr><th>Rua</th>${zones.map(z=>`<th>${z}</th>`).join('')}</tr></thead><tbody>${roads.map(r=>`<tr><th>${String(r).padStart(2,'0')}</th>${zones.map(z=>cell(map.get(`${z}|${r}`))).join('')}</tr>`).join('')}</tbody></table>`}
function cell(x){if(!x)return'<td class="no-data">—</td>';const v=+x.occ_pct,k=v>=90?'critical':v>=75?'attention':'available';return`<td class="${k}"><strong>${pct(v)}</strong><small>${num(x.real_pieces)} pç</small></td>`}function match(x,r){const v=+x.occ_pct;return r==='ALL'||r==='CRITICAL'&&v>=90||r==='ATTENTION'&&v>=75&&v<90||r==='AVAILABLE'&&v<75}
async function canvas(){await libs();return html2canvas($('.report-shell'),{scale:2,backgroundColor:'#eef1f4',useCORS:true,logging:false})}
async function copyImage(){const b=$('#copyImageBtn');button(b,'Gerando imagem...');try{const c=await canvas(),blob=await new Promise(ok=>c.toBlob(ok,'image/png'));if(!blob)throw Error('Imagem indisponível');if(navigator.clipboard&&window.ClipboardItem){await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);button(b,'Imagem copiada',1800)}else{download(blob,'BRFRS1-reporte.png');button(b,'Imagem baixada',1800)}}catch(e){console.error(e);status('Não foi possível copiar; tentando baixar a imagem.',true);try{const c=await canvas();c.toBlob(x=>download(x,'BRFRS1-reporte.png'),'image/png');button(b,'Imagem baixada',1800)}catch{button(b,'Tentar novamente',1800)}}}
async function exportPdf(){const b=$('#exportPdfBtn');button(b,'Gerando PDF...');try{const c=await canvas(),pdf=new jspdf.jsPDF({orientation:c.width>c.height?'landscape':'portrait',unit:'mm',format:'a4'}),w=pdf.internal.pageSize.getWidth(),h=pdf.internal.pageSize.getHeight(),ih=c.height*w/c.width,img=c.toDataURL('image/png');let remain=ih,pos=0;pdf.addImage(img,'PNG',0,pos,w,ih);remain-=h;while(remain>0){pos=remain-ih;pdf.addPage();pdf.addImage(img,'PNG',0,pos,w,ih);remain-=h}pdf.save(`BRFRS1-reporte-${new Date().toISOString().slice(0,10)}.pdf`);button(b,'PDF baixado',1800)}catch(e){console.error(e);status('Falha ao gerar PDF. Tente novamente.',true);button(b,'Exportar PDF',1800)}}
function libs(){return Promise.all([lib('https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js','html2canvas'),lib('https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js','jspdf')])}function lib(src,key){if(window[key])return Promise.resolve();return new Promise((ok,no)=>{const old=document.querySelector(`[data-export="${key}"]`);if(old){old.addEventListener('load',ok,{once:true});old.addEventListener('error',no,{once:true});return}const s=document.createElement('script');s.src=src;s.dataset.export=key;s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}function button(b,label,back){const original=b.id==='copyImageBtn'?'Copiar imagem':'Exportar PDF';b.textContent=label;if(back)setTimeout(()=>b.textContent=original,back)}function status(text,bad){const e=$('#reportStatus');e.textContent=text;e.style.color=bad?'#b91c1c':''}function num(v){return Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:0})}function pct(v){return v==null||Number.isNaN(Number(v))?'—':`${Number(v).toLocaleString('pt-BR',{maximumFractionDigits:1})}%`}function date(v){const d=new Date(v);return Number.isNaN(d.getTime())?String(v||'—'):d.toLocaleString('pt-BR')}
