
const $=s=>document.querySelector(s);let data,scene,camera,renderer,controls,group,zone,level='all';const params=new URLSearchParams(location.search);document.addEventListener('DOMContentLoaded',init);
async function init(){status('loading','Carregando');try{data=await WMS.load();ui();setup();render();status('ok',WMS.config.SHEET_API_URL?'Google Sheets conectado':'Modo local')}catch(e){status('error','Erro na conexão');console.error(e)}}
function ui(){const zs=WMS.zones(data);$('#zoneSelect').innerHTML=zs.map(z=>`<option>${z}</option>`).join('');zone=params.get('zone')||WMS.config.DEFAULT_ZONE||zs[0];if(!zs.includes(zone))zone=zs[0];$('#zoneSelect').value=zone;$('#zoneSelect').onchange=e=>{zone=e.target.value;fillLevels();render()};fillLevels();const lv=params.get('level');if(lv){level=lv;$('#levelSelect').value=lv}$('#levelSelect').onchange=e=>{level=e.target.value;render()};$('#searchInput').value=params.get('road')?`${zone}-${params.get('road')}-${lv||'01'}-001`:'';$('#searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')search()});$('#droneBtn').onclick=()=>{camera.position.set(0,70,45);controls.target.set(0,0,0)};$('#operatorBtn').onclick=()=>{camera.position.set(0,2.2,28);controls.target.set(0,2.2,0)}}
function fillLevels(){const ls=[...new Set(data.cells.filter(c=>String(c.Zona)===zone).map(c=>+c.nivel))].sort((a,b)=>a-b);$('#levelSelect').innerHTML='<option value="all">Todos</option>'+ls.map(l=>`<option value="${l}">Nível ${String(l).padStart(2,'0')}</option>`).join('')}
function setup(){const h=$('#viewer');scene=new THREE.Scene();scene.background=new THREE.Color(0xeaf1f7);scene.fog=new THREE.Fog(0xeaf1f7,80,260);camera=new THREE.PerspectiveCamera(55,h.clientWidth/h.clientHeight,.1,1000);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));renderer.setSize(h.clientWidth,h.clientHeight);h.appendChild(renderer.domElement);controls=new THREE.OrbitControls(camera,renderer.domElement);controls.enableDamping=true;scene.add(new THREE.HemisphereLight(0xffffff,0x8999aa,2));const d=new THREE.DirectionalLight(0xffffff,1.5);d.position.set(30,50,20);scene.add(d);const f=new THREE.Mesh(new THREE.PlaneGeometry(220,150),new THREE.MeshStandardMaterial({color:0xdce5ed,roughness:.9}));f.rotation.x=-Math.PI/2;scene.add(f);scene.add(new THREE.GridHelper(200,80,0xb8c5d1,0xcbd5df));group=new THREE.Group();scene.add(group);addEventListener('resize',()=>{camera.aspect=h.clientWidth/h.clientHeight;camera.updateProjectionMatrix();renderer.setSize(h.clientWidth,h.clientHeight)});renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)})}
function render(){while(group.children.length){const o=group.children.pop();o.geometry?.dispose();o.material?.dispose()}const cs=data.cells.filter(c=>String(c.Zona)===zone&&(level==='all'||+c.nivel===+level)),rs=[...new Set(cs.map(c=>+c.rua_num))].sort((a,b)=>a-b),ls=[...new Set(cs.map(c=>+c.nivel))].sort((a,b)=>a-b),map=new Map(cs.map(c=>[`${c.rua_num}|${c.nivel}`,c])),gap=3.8,len=30,off=(rs.length-1)*gap/2;rs.forEach((r,i)=>{const x=i*gap-off;frame(x,len,Math.max(...ls,1)*2.1+1);ls.forEach(l=>{const c=map.get(`${r}|${l}`);if(!c)return;const m=new THREE.Mesh(new THREE.BoxGeometry(2.6,1.35,len-1),new THREE.MeshStandardMaterial({color:color(c.occ_pct),roughness:.72,transparent:true,opacity:.88}));m.position.set(x,l*2.1-.5,0);group.add(m)})});camera.position.set(Math.max(25,rs.length*2.4),Math.max(24,ls.length*4),45);controls.target.set(0,ls.length*1.05,0);$('#viewerInfo').textContent=`Zona ${zone} · ${rs.length} ruas · ${ls.length} níveis · ${WMS.fmt(cs.length)} células`}
function frame(x,len,h){const g=new THREE.MeshStandardMaterial({color:0x566575,metalness:.3}),o=new THREE.MeshStandardMaterial({color:0xf97316});[-1.45,1.45].forEach(dx=>[-len/2,len/2].forEach(z=>{const p=new THREE.Mesh(new THREE.BoxGeometry(.16,h,.16),g);p.position.set(x+dx,h/2,z);group.add(p)}));for(let y=1.5;y<h;y+=2.1)[-1.45,1.45].forEach(dx=>{const b=new THREE.Mesh(new THREE.BoxGeometry(.18,.16,len),o);b.position.set(x+dx,y,0);group.add(b)})}
function search(){const m=$('#searchInput').value.toUpperCase().match(/([A-Z0-9]+)[-_\/](\d+)[-_\/](\d+)/);if(!m)return;zone=m[1];level=String(+m[3]);$('#zoneSelect').value=zone;fillLevels();$('#levelSelect').value=level;render()}function color(v){v=+v;if(!Number.isFinite(v))return 0x94a3b8;return v>=90?0xef4444:v>=75?0xf59e0b:v>=40?0x22c55e:0x94a3b8}function status(c,t){$('#status').className=`status ${c}`;$('#status').innerHTML=`<i></i>${t}`}
